# Generated by Django 5.2.1 on 2025-05-15 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                ("breed_id", models.AutoField(primary_key=True, serialize=False)),
                ("breed_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                ("feed_id", models.AutoField(primary_key=True, serialize=False)),
                ("feed_type", models.TextField()),
                ("amount_taken", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                ("medicine_id", models.AutoField(primary_key=True, serialize=False)),
                ("medicine_name", models.TextField()),
                ("amount_taken", models.IntegerField()),
                ("expiry_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("isAdmin", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ChickenBatch",
            fields=[
                ("batch_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_name", models.TextField()),
                ("batch_age", models.TextField()),
                ("weight", models.IntegerField()),
                ("isHealthGood", models.BooleanField(default=True)),
                ("Date_Arrived", models.DateField()),
                ("Date_Released", models.DateField(blank=True, null=True)),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Poultry.breed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrowthLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("log_date", models.DateField()),
                ("weight", models.FloatField()),
                ("isHealthGood", models.BooleanField(default=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Poultry.chickenbatch",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Poultry.feed",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Poultry.medicine",
                    ),
                ),
            ],
        ),
    ]
