# Generated by Django 5.2.1 on 2025-05-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poultry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='amount_taken',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='amount_taken',
            new_name='quantity',
        ),
    ]
